---
title: "project folders"
output: html_document
date: "2024-09-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Using a consistent folder structure across your projects will help keep things
organized, and will help you to find/file things in the future. This
can be especially helpful when you have multiple projects.



Best practice teaches you its good to always have atleast 4 kinds of folders in your project folder:

- **`data_raw/` \& `data/`** Use these folders to store raw data and
  intermediate datasets you may create for the need of a particular analysis.
  For the sake of transparency and
  [provenance](https://en.wikipedia.org/wiki/Provenance), you should *always*
  keep a copy of your raw data accessible and do as much of your data cleanup
  and preprocessing programmatically (i.e., with scripts, rather than
  manually) as possible. Separating raw data from processed data is also a
  good idea. For example, you could have files
  `data_raw/tree_survey.plot1.txt` and `...plot2.txt` kept separate from a
  `data/tree.survey.csv` file generated by the
  `scripts/01.preprocess.tree_survey.R` script.
- **`documents/`** This would be a place to keep outlines, drafts, and other
  text.
- **`scripts/`** This would be the location to keep your R scripts for
  different analyses or plotting, and potentially a separate folder for your
  functions (more on that later).
- **Additional (sub)directories** depending on your project needs.
